spring.application.name=Standup-App

# Server Configuration
server.port=5555

# Environment Variables for Authentication
auth.username=${AUTH_USERNAME:}
auth.password=${AUTH_PASSWORD:}
auth.secret.key=${FLASK_SECRET_KEY:}

# CSRF Configuration
csrf.time.limit=${WTF_CSRF_TIME_LIMIT:3600}

# File Storage Configuration
standups.file=${STANDUPS_FILE:data/Standups.txt}

# Discord Webhook
discord.webhook.url=${DISCORD_WEBHOOK_URL:}

# Logging Configuration
logging.level.com.shivank.Standup_App=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

# Health Check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
